Repository Argonaut-B04/SIRIO, pull requests merged in 2020-05, with the labels that each got.

#193 Fix: Issue and Database Init
  BackEnd/src/main/resources/application.properties
  BackEnd/src/main/resources/data-mysql.sql
  FrontEnd/src/Components/Tables/RiskRating/TableRiskRating.jsx
  FrontEnd/src/Components/Tables/SirioTable.jsx
Labels: bug, enhancement

#194 Feat: component chart and examples
  FrontEnd/package-lock.json
  FrontEnd/package.json
  FrontEnd/src/Components/Chart/SirioBarChart.jsx
  FrontEnd/src/pages/index.jsx
Labels: enhancement

#195 Feat: Dashboard Box
  FrontEnd/src/Components/Box/SirioDashboardBox.jsx
  FrontEnd/src/Components/Box/SirioDashboardBox.module.css
  FrontEnd/src/Components/Box/SirioDashboardItem.jsx
  FrontEnd/src/pages/index.jsx
Labels: enhancement

#196 Fix: Bugs on Hierarki Risiko
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RisikoRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestServiceImpl.java
  FrontEnd/package.json
  FrontEnd/src/Components/Form/DemoForm/DemoForm.jsx
  FrontEnd/src/Components/Form/DemoForm/DemoMultiForm.jsx
  FrontEnd/src/Components/Form/HierarkiRisiko/FormHierarkiRisiko.jsx
  FrontEnd/src/pages/formMultiPage.jsx
  FrontEnd/src/pages/formPage.jsx
Labels: bug

#198 Cloud/uc1 hasil pemeriksaan
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/HasilPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/TugasPemeriksaanRestController.java
  FrontEnd/src/Components/Button/ActionButton/SirioConfirmButton.jsx
  FrontEnd/src/Components/DetailPages/HasilPemeriksaan/DetailHasilPemeriksaan.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormTambah.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormTolak.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormUbah.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.jsx
Labels: bug, enhancement

#200 Backend: Database Initialization Performance
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/DatabaseLoader.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestServiceImpl.java
  BackEnd/src/main/resources/application.properties
  BackEnd/src/main/resources/data-mysql.sql
Labels: enhancement

#199 Dina/registrasi risiko
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/DashboardStaffController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/HasilPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RisikoRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/AccessPermissions.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Risiko.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/RisikoDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/DashboardDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/RisikoDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RisikoRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RisikoRestServiceImpl.java
  FrontEnd/package-lock.json
  FrontEnd/package.json
  FrontEnd/src/App.js
  FrontEnd/src/Components/DetailPages/RegistrasiRisiko/DetailRisiko.jsx
  FrontEnd/src/Components/Form/HierarkiRisiko/FormHierarkiRisiko.jsx
  FrontEnd/src/Components/Form/RegistrasiRisiko/FormRisiko.jsx
  FrontEnd/src/Components/Form/RegistrasiRisiko/FormRisikoUbah.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.module.css
  FrontEnd/src/Components/SideNav/RoleSideNav/SuperuserSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/SupervisorSideNav.jsx
  FrontEnd/src/Configuration/UrlConfig.jsx
  FrontEnd/src/Services/DashboardStaffService.jsx
  FrontEnd/src/Services/RegistrasiRisikoService.jsx
  FrontEnd/src/pages/Supervisor/DashboadStaff.jsx
Labels: enhancement

#201 Cloud/uc1 hasil pemeriksaan
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/EmployeeRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/HasilPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Employee.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/KomponenPemeriksaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Rekomendasi.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/TemuanRisiko.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/EmployeeDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/KomponenPemeriksaanDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KomponenPemeriksaanRestServiceImpl.java
  BackEnd/src/main/resources/data-mysql.sql
  FrontEnd/src/Components/DetailPages/HasilPemeriksaan/DetailHasilPemeriksaan.jsx
  FrontEnd/src/Components/Form/Employee/EmployeeFormTambah.jsx
  FrontEnd/src/Components/Form/Employee/EmployeeFormUbah.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormTambah.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormTolak.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormUbah.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.jsx
  FrontEnd/src/Components/Tables/Employee/TabelEmployee.jsx
  FrontEnd/src/Services/EmployeeService.jsx
  FrontEnd/src/Services/HasilPemeriksaanService.jsx
Labels: enhancement

#202 Cloud/uc1 hasil pemeriksaan
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/HasilPemeriksaanRestController.java
  BackEnd/src/main/resources/data-mysql.sql
  FrontEnd/src/Components/DetailPages/HasilPemeriksaan/DetailHasilPemeriksaan.jsx
  FrontEnd/src/Components/DetailPages/SirioDetailPage.jsx
  FrontEnd/src/Components/Dropdown/SirioSelect.jsx
  FrontEnd/src/Components/Form/Employee/EmployeeFormTambah.jsx
  FrontEnd/src/Components/Form/Employee/EmployeeFormUbah.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormTambah.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormUbah.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.jsx
Labels: enhancement

#203 feat: update input validation process in hasil pemeriksaan and employee
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/EmployeeRestController.java
  FrontEnd/src/Components/Dropdown/SirioSelect.jsx
  FrontEnd/src/Components/Form/Employee/EmployeeFormTambah.jsx
  FrontEnd/src/Components/Form/Employee/EmployeeFormUbah.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormTambah.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormUbah.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.jsx
  FrontEnd/src/Services/HasilPemeriksaanService.jsx
Labels: enhancement

#204 Update: Frontend
  FrontEnd/src/Components/Button/ActionButton/ActionButton.module.css
  FrontEnd/src/Components/Button/ActionButton/SirioConfirmButton.jsx
  FrontEnd/src/Components/Button/ActionButton/SirioMessageButton.jsx
  FrontEnd/src/Components/Button/ActionButton/SirioModal.jsx
  FrontEnd/src/Components/Button/ActionButton/SirioWarningButton.jsx
  FrontEnd/src/Components/Button/ActionButton/TriggerButton.jsx
  FrontEnd/src/Components/DetailPages/SirioDetailPage.module.css
  FrontEnd/src/Components/Form/DemoForm/DemoForm.jsx
  FrontEnd/src/Components/Form/LoginForm.jsx
  FrontEnd/src/Components/Form/Reminder/ReminderTemplateForm.jsx
  FrontEnd/src/Components/SideNav/SideNavFramework.jsx
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
  FrontEnd/src/Components/Tables/Reminder/TabelReminder.jsx
  FrontEnd/src/Components/Tables/RiskLevel/TableRiskLevel.jsx
  FrontEnd/src/Components/Tables/RiskRating/TableRiskRating.jsx
  FrontEnd/src/Components/Tables/SirioTable.jsx
  FrontEnd/src/Layout/SirioMainLayout.jsx
  FrontEnd/src/pages/QAOfficer/Reminder.jsx
  FrontEnd/src/pages/QAOfficer/TemplateReminder.jsx
Labels: bug, enhancement

#205 Feat: auto create 3 reminder on set dateline
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RekomendasiRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderRestServiceImpl.java
Labels: enhancement

#206 Dina/registrasi risiko
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/DashboardStaffController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/DashboardDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RisikoRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TemuanRisikoRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TemuanRisikoRestServiceImpl.java
  FrontEnd/src/Components/Dropdown/SirioSelect.jsx
  FrontEnd/src/Components/Form/HierarkiRisiko/FormHierarkiRisiko.jsx
  FrontEnd/src/Components/Form/RegistrasiRisiko/FormRisiko.jsx
  FrontEnd/src/Components/Form/RegistrasiRisiko/FormRisikoUbah.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.jsx
  FrontEnd/src/pages/Supervisor/DashboadStaff.jsx
Labels: bug

#207 fix: fix email validation in edit employee form
  FrontEnd/src/Components/Form/Employee/EmployeeFormTambah.jsx
  FrontEnd/src/Components/Form/Employee/EmployeeFormUbah.jsx
Labels: bug

#208 Greta/all bukti pelaksanaan
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/BuktiPelaksanaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RekomendasiRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/BuktiPelaksanaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/BuktiPelaksanaanDTO.java
  FrontEnd/src/Components/DetailPages/BuktiPelaksanaan/DetailBuktiPelaksanaan.jsx
  FrontEnd/src/Components/Form/BuktiPelaksanaan/FormTambahBukti.jsx
  FrontEnd/src/Components/Form/BuktiPelaksanaan/FormTolakBukti.jsx
  FrontEnd/src/Components/Form/BuktiPelaksanaan/FormUbahBukti.jsx
  FrontEnd/src/Components/Tables/BuktiPelaksanaan/TabelBuktiPelaksanaan.jsx
  FrontEnd/src/Services/BuktiPelaksanaanService.jsx
Labels: enhancement

#210 Dina/registrasi risiko
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/DashboardStaffController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/EmployeeRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RisikoRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/TemuanRisikoDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/DashboardDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RisikoRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RisikoRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TemuanRisikoRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TemuanRisikoRestServiceImpl.java
  BackEnd/src/main/resources/data-mysql.sql
  FrontEnd/src/App.js
  FrontEnd/src/Components/Box/SirioDashboardBox.jsx
  FrontEnd/src/Components/Box/SirioDashboardBox.module.css
  FrontEnd/src/Components/DetailPages/RegistrasiRisiko/DetailRisiko.jsx
  FrontEnd/src/Components/Dropdown/SirioSelect.jsx
  FrontEnd/src/Components/Dropdown/SirioSelect.module.css
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.jsx
  FrontEnd/src/Components/Header/SirioComponentHeader.module.css
  FrontEnd/src/Services/DashboardStaffService.jsx
  FrontEnd/src/Services/EmployeeService.jsx
  FrontEnd/src/pages/Supervisor/DashboadStaff.jsx
  FrontEnd/src/pages/Supervisor/DashboardStaff.jsx
Labels: enhancement

#211 Dina/registrasi risiko
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/DashboardStaffController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestServiceImpl.java
  FrontEnd/src/Components/DetailPages/RegistrasiRisiko/DetailRisiko.jsx
  FrontEnd/src/Components/Form/HierarkiRisiko/FormHierarkiRisiko.jsx
  FrontEnd/src/Components/Form/RegistrasiRisiko/FormRisiko.jsx
  FrontEnd/src/Components/Form/RegistrasiRisiko/FormRisikoUbah.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/QAOfficerSideNav.jsx
  FrontEnd/src/Components/Tables/RegistrasiRisiko/TabelRisiko.jsx
  FrontEnd/src/pages/ManagerOR/DetailRisiko.jsx
  FrontEnd/src/pages/ManagerOR/FormRisiko.jsx
  FrontEnd/src/pages/ManagerOR/FormRisikoUbah.jsx
  FrontEnd/src/pages/ManagerOR/HierarkiRisiko.jsx
  FrontEnd/src/pages/ManagerOR/RegistrasiRisiko.jsx
  FrontEnd/src/pages/Supervisor/DashboardStaff.jsx
Labels: enhancement

#212 feat: menambahkan akses untuk qa lead dan superqa
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/DashboardStaffController.java
  FrontEnd/src/Components/SideNav/RoleSideNav/QALeadSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/SuperQASideNav.jsx
  FrontEnd/src/pages/Supervisor/DashboardStaff.jsx
Labels: bug, enhancement

#213 Cloud/uc1 hasil pemeriksaan
  FrontEnd/src/Components/DetailPages/Employee/DetailEmployee.jsx
  FrontEnd/src/Components/DetailPages/HasilPemeriksaan/DetailHasilPemeriksaan.jsx
  FrontEnd/src/Components/Form/Employee/EmployeeFormTambah.jsx
  FrontEnd/src/Components/Form/Employee/EmployeeFormUbah.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormTambah.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormTolak.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormUbah.jsx
  FrontEnd/src/Components/Tables/Employee/TabelEmployee.jsx
  FrontEnd/src/Components/Tables/HasilPemeriksaan/TabelHasilPemeriksaan.jsx
  FrontEnd/src/Components/Tables/TugasPemeriksaan/TabelTugasPemeriksaan.jsx
  FrontEnd/src/pages/Administrator/DaftarEmployee.jsx
  FrontEnd/src/pages/Administrator/DetailEmployee.jsx
  FrontEnd/src/pages/Administrator/FormTambahEmployee.jsx
  FrontEnd/src/pages/Administrator/FormUbahEmployee.jsx
  FrontEnd/src/pages/QAOfficer/DaftarHasilPemeriksaan.jsx
  FrontEnd/src/pages/QAOfficer/DaftarTugasPemeriksaan.jsx
  FrontEnd/src/pages/QAOfficer/DetailHasilPemeriksaan.jsx
  FrontEnd/src/pages/QAOfficer/FormTambahHasilPemeriksaan.jsx
  FrontEnd/src/pages/QAOfficer/FormTolakHasilPemeriksaan.jsx
  FrontEnd/src/pages/QAOfficer/FormUbahHasilPemeriksaan.jsx
Labels: enhancement

#216 fix: memperbaiki dashboard divisi
  FrontEnd/src/pages/Supervisor/DashboardStaff.jsx
Labels: bug

#222 feat: add frontend button hasil pemeriksaan jalankan
  FrontEnd/src/Components/Form/Employee/EmployeeFormTambah.jsx
  FrontEnd/src/Components/Tables/HasilPemeriksaan/TabelHasilPemeriksaan.jsx
Labels: enhancement

#224 Cloud/uc1 hasil pemeriksaan
  FrontEnd/src/Components/DetailPages/Employee/DetailEmployee.jsx
  FrontEnd/src/Components/DetailPages/HasilPemeriksaan/DetailHasilPemeriksaan.jsx
  FrontEnd/src/Components/Form/Employee/EmployeeFormTambah.jsx
  FrontEnd/src/Components/Form/Employee/EmployeeFormUbah.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormTambah.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormTolak.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormUbah.jsx
  FrontEnd/src/Components/Tables/HasilPemeriksaan/TabelHasilPemeriksaan.jsx
Labels: bug

#226 Cloud/uc1 hasil pemeriksaan
  FrontEnd/src/Components/Form/Employee/EmployeeFormTambah.jsx
  FrontEnd/src/Components/Form/Employee/EmployeeFormUbah.jsx
Labels: bug

#227 Cloud/uc1 hasil pemeriksaan
  FrontEnd/src/Components/Form/Employee/EmployeeFormTambah.jsx
  FrontEnd/src/Components/Form/Employee/EmployeeFormUbah.jsx
Labels: bug
