Repository Argonaut-B04/SIRIO, pull requests merged in 2020-03, with the labels that each got.

#1 Initializing Spring Boot Project
  .gitignore
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/ArgonautB04/SIRIO/SirioApplication.java
  src/main/resources/application.properties
  src/test/java/com/ArgonautB04/SIRIO/SirioApplicationTests.java
Labels: enhancement

#10 Completing all Models
  pom.xml
  src/main/java/com/ArgonautB04/SIRIO/model/BuktiPelaksanaan.java
  src/main/java/com/ArgonautB04/SIRIO/model/Employee.java
  src/main/java/com/ArgonautB04/SIRIO/model/HasilPemeriksaan.java
  src/main/java/com/ArgonautB04/SIRIO/model/KantorCabang.java
  src/main/java/com/ArgonautB04/SIRIO/model/KomponenPemeriksaan.java
  src/main/java/com/ArgonautB04/SIRIO/model/Rekomendasi.java
  src/main/java/com/ArgonautB04/SIRIO/model/Reminder.java
  src/main/java/com/ArgonautB04/SIRIO/model/RencanaPemeriksaan.java
  src/main/java/com/ArgonautB04/SIRIO/model/Risiko.java
  src/main/java/com/ArgonautB04/SIRIO/model/RiskLevel.java
  src/main/java/com/ArgonautB04/SIRIO/model/RiskRating.java
  src/main/java/com/ArgonautB04/SIRIO/model/Role.java
  src/main/java/com/ArgonautB04/SIRIO/model/SOP.java
  src/main/java/com/ArgonautB04/SIRIO/model/StatusBuktiPelaksanaan.java
  src/main/java/com/ArgonautB04/SIRIO/model/StatusHasilPemeriksaan.java
  src/main/java/com/ArgonautB04/SIRIO/model/StatusRekomendasi.java
  src/main/java/com/ArgonautB04/SIRIO/model/StatusRencanaPemeriksaan.java
  src/main/java/com/ArgonautB04/SIRIO/model/StatusRisiko.java
  src/main/java/com/ArgonautB04/SIRIO/model/TemuanRisiko.java
  src/main/java/com/ArgonautB04/SIRIO/model/TugasPemeriksaan.java
  src/main/java/com/ArgonautB04/SIRIO/repository/BuktiPelaksanaanRepo.java
  src/main/java/com/ArgonautB04/SIRIO/repository/EmployeeRepo.java
  src/main/java/com/ArgonautB04/SIRIO/repository/HasilPemeriksaanRepo.java
  src/main/java/com/ArgonautB04/SIRIO/repository/KantorCabangRepo.java
  src/main/java/com/ArgonautB04/SIRIO/repository/KomponenPemeriksaanRepo.java
  src/main/java/com/ArgonautB04/SIRIO/repository/RekomendasiRepo.java
  src/main/java/com/ArgonautB04/SIRIO/repository/ReminderRepo.java
  src/main/java/com/ArgonautB04/SIRIO/repository/RencanaPemeriksaanRepo.java
  src/main/java/com/ArgonautB04/SIRIO/repository/RisikoRepo.java
  src/main/java/com/ArgonautB04/SIRIO/repository/RiskLevelRepo.java
  src/main/java/com/ArgonautB04/SIRIO/repository/RiskRatingRepo.java
  src/main/java/com/ArgonautB04/SIRIO/repository/RoleRepo.java
  src/main/java/com/ArgonautB04/SIRIO/repository/SOPRepo.java
  src/main/java/com/ArgonautB04/SIRIO/repository/StatusBuktiPelaksanaanRepo.java
  src/main/java/com/ArgonautB04/SIRIO/repository/StatusHasilPemeriksaanRepo.java
  src/main/java/com/ArgonautB04/SIRIO/repository/StatusRekomendasiRepo.java
  src/main/java/com/ArgonautB04/SIRIO/repository/StatusRencanaPemeriksaanRepo.java
  src/main/java/com/ArgonautB04/SIRIO/repository/StatusRisikoRepo.java
  src/main/java/com/ArgonautB04/SIRIO/repository/TemuanRIsikoRepo.java
  src/main/java/com/ArgonautB04/SIRIO/repository/TugasPemeriksaanRepo.java
  src/main/resources/application.properties
Labels: enhancement

#13 Division of Backend and Frontend
  BackEnd/.gitignore
  BackEnd/.mvn/wrapper/MavenWrapperDownloader.java
  BackEnd/.mvn/wrapper/maven-wrapper.jar
  BackEnd/.mvn/wrapper/maven-wrapper.properties
  BackEnd/mvnw
  BackEnd/mvnw.cmd
  BackEnd/pom.xml
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/SirioApplication.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/BuktiPelaksanaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Employee.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/HasilPemeriksaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/KantorCabang.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/KomponenPemeriksaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Rekomendasi.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Reminder.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/RencanaPemeriksaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Risiko.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/RiskLevel.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/RiskRating.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Role.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/SOP.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/StatusBuktiPelaksanaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/StatusHasilPemeriksaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/StatusRekomendasi.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/StatusRencanaPemeriksaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/StatusRisiko.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/TemuanRisiko.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/TugasPemeriksaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/BuktiPelaksanaanRepo.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/EmployeeRepo.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/HasilPemeriksaanRepo.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/KantorCabangRepo.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/KomponenPemeriksaanRepo.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/RekomendasiRepo.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/ReminderRepo.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/RencanaPemeriksaanRepo.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/RisikoRepo.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/RiskLevelRepo.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/RiskRatingRepo.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/RoleRepo.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/SOPRepo.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/StatusBuktiPelaksanaanRepo.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/StatusHasilPemeriksaanRepo.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/StatusRekomendasiRepo.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/StatusRencanaPemeriksaanRepo.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/StatusRisikoRepo.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/TemuanRIsikoRepo.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/TugasPemeriksaanRepo.java
  BackEnd/src/main/resources/application.properties
  BackEnd/src/test/java/com/ArgonautB04/SIRIO/SirioApplicationTests.java
Labels: change of directory

#16 Frontend: Init React App
  FrontEnd/.gitignore
  FrontEnd/README.md
  FrontEnd/package-lock.json
  FrontEnd/package.json
  FrontEnd/public/favicon.ico
  FrontEnd/public/index.html
  FrontEnd/public/logo192.png
  FrontEnd/public/logo512.png
  FrontEnd/public/manifest.json
  FrontEnd/public/robots.txt
  FrontEnd/src/App.css
  FrontEnd/src/App.js
  FrontEnd/src/App.test.js
  FrontEnd/src/index.css
  FrontEnd/src/index.js
  FrontEnd/src/logo.svg
  FrontEnd/src/serviceWorker.js
  FrontEnd/src/setupTests.js
Labels: enhancement

#17 Pull Request Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#18 Standarisasi DTO Selesai
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/data_transfer_object/BaseResponse.java
Labels: enhancement

#19 Main Functions for All Classes
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Employee.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/HasilPemeriksaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/KantorCabang.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/TemuanRisiko.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/TemuanRisikoRepo.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/BuktiPelaksanaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/BuktiPelaksananRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/HasilPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/HasilPemeriksaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KantorCabangRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KantorCabangRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KomponenPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KomponenPemeriksaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RencanaPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RencanaPemeriksaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RisikoRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RisikoRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RiskLevelRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RiskLevelRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RiskRatingRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RiskRatingRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RoleRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RoleRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/SOPRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/SOPRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusBuktiPelaksanaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusBuktiPelaksanaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusHasilPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusHasilPemeriksaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusRekomendasiRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusRekomendasiRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusRencanaPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusRencanaPemeriksaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusRisikoRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusRisikoRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TemuanRisikoRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TemuanRisikoRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TugasPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TugasPemeriksaanRestServiceImpl.java
Labels: enhancement

#21 Style: space and if-else brances
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/BuktiPelaksananRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/HasilPemeriksaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KantorCabangRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KomponenPemeriksaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RencanaPemeriksaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RisikoRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RiskLevelRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RiskRatingRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RoleRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/SOPRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusBuktiPelaksanaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusHasilPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusHasilPemeriksaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusRekomendasiRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusRencanaPemeriksaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusRisikoRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TemuanRisikoRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TugasPemeriksaanRestServiceImpl.java
Labels: Style

#22 feat: get-all for all services
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/BuktiPelaksanaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/BuktiPelaksananRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/HasilPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/HasilPemeriksaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KantorCabangRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KantorCabangRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KomponenPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KomponenPemeriksaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RencanaPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RencanaPemeriksaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RisikoRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RisikoRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RiskLevelRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RiskLevelRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RiskRatingRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RiskRatingRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RoleRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RoleRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/SOPRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/SOPRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusBuktiPelaksanaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusBuktiPelaksanaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusHasilPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusHasilPemeriksaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusRekomendasiRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusRekomendasiRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusRencanaPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusRencanaPemeriksaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusRisikoRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusRisikoRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TemuanRisikoRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TemuanRisikoRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TugasPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TugasPemeriksaanRestServiceImpl.java
Labels: enhancement

#23 Contribution Guideline
  .github/CONTRIBUTING.md
Labels: documentation

#31 Init All Controller Class
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/BuktiPelaksanaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/EmployeeRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/HasilPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/KantorCabangRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/KomponenPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RekomendasiRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/ReminderRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RencanaPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RisikoRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RiskLevelRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RiskRatingRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RoleRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/SOPRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/StatusBuktiPelaksanaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/StatusHasilPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/StatusRekomendasiRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/StatusRencanaPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/StatusRisikoRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/TemuanRisikoRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/TugasPemeriksaanRestController.java
Labels: enhancement

#36 Tenggat Waktu dan Reminder Backend
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RekomendasiRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/ReminderRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Reminder.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Risiko.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/RekomendasiDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/ReminderDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/BaseResponse.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/ReminderDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/Settings.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderRestServiceImpl.java
Labels: enhancement

#37 Nathanael/uc5 tenggat waktu
  FrontEnd/package-lock.json
  FrontEnd/package.json
  FrontEnd/src/App.js
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.js
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.module.css
  FrontEnd/src/pages/DaftarRekomendasi.js
  FrontEnd/src/pages/error.js
  FrontEnd/src/pages/index.js
Labels: enhancement

#38 Feat: Change ubah tenggat waktu url
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RekomendasiRestController.java
Labels: enhancement

#40 Populate Statuses
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/StatusBuktiPelaksanaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/StatusHasilPemeriksaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/StatusRekomendasi.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/StatusRencanaPemeriksaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/StatusRisiko.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/DatabaseLoader.java
Labels: enhancement

#46 Feat: connecting rekomendasi and kantor cabang
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Rekomendasi.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/RekomendasiDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestServiceImpl.java
Labels: enhancement

#41 Cloud/uc1 hasil pemeriksaan
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/HasilPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/HasilPemeriksaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/KomponenPemeriksaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Rekomendasi.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/TemuanRisiko.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/HasilPemeriksaanDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/KomponenPemeriksaanDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/RekomendasiDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/TemuanRisikoDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/HasilPemeriksaanDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/KomponenPemeriksaanDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/RekomendasiDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/TemuanRisikoDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/HasilPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/HasilPemeriksaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KomponenPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KomponenPemeriksaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TemuanRisikoRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TemuanRisikoRestServiceImpl.java
Labels: enhancement

#48 Cloud/uc1 hasil pemeriksaan
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/TugasPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/TugasPemeriksaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/TugasPemeriksaanDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TugasPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TugasPemeriksaanRestServiceImpl.java
Labels: enhancement

#49 feat: add approval function for approve or reject hasil pemeriksaan
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/HasilPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Rekomendasi.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/RekomendasiDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/PersetujuanHasilPemeriksaanDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/RekomendasiDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestServiceImpl.java
Labels: enhancement

#50 Rekomendasi dan Kantor Cabang
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RekomendasiRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Rekomendasi.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/StatusRekomendasi.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/TugasPemeriksaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/HasilPemeriksaanDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/KomponenPemeriksaanDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/RekomendasiDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/TugasPemeriksaanDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/DatabaseLoader.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/HasilPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/HasilPemeriksaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KomponenPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KomponenPemeriksaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TugasPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TugasPemeriksaanRestServiceImpl.java
Labels: enhancement

#52 Tenggat Waktu and FrontEnd
  FrontEnd/public/logo.png
  FrontEnd/public/sidePattern.png
  FrontEnd/src/App.js
  FrontEnd/src/App.test.js
  FrontEnd/src/Components/SideNav/SideNav.jsx
  FrontEnd/src/Components/SideNav/SideNav.module.css
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
  FrontEnd/src/pages/DaftarRekomendasi.js
  FrontEnd/src/pages/DaftarRekomendasi.jsx
  FrontEnd/src/pages/DaftarRekomendasi.module.css
  FrontEnd/src/pages/error.jsx
  FrontEnd/src/pages/index.jsx
Labels: enhancement

#54 Documentation and Minor Wording
  .github/CONTRIBUTING.md
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Risiko.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RisikoRestServiceImpl.java
  README.md
Labels: documentation

#56 Daftar Rekomendasi Frontend
  FrontEnd/package-lock.json
  FrontEnd/package.json
  FrontEnd/src/Components/Button/DatePickerButton.jsx
  FrontEnd/src/Components/Button/TableButton.jsx
  FrontEnd/src/Components/Button/TableButton.module.css
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.module.css
Labels: enhancement

#59 Feat/mengelola bukti pelaksanaan
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/BuktiPelaksanaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/BuktiPelaksanaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/BuktiPelaksanaanDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/BuktiPelaksanaanDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/RekomendasiDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/BuktiPelaksanaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/BuktiPelaksananRestServiceImpl.java
Labels: enhancement

#61 Perf: change Risiko status from class to enum
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Risiko.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/DatabaseLoader.java
Labels: enhancement

#62 Revisi Model, Controller, dan Service dari UC5
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RekomendasiRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/ReminderRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Risiko.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/RekomendasiDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/ReminderDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RisikoRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RisikoRestServiceImpl.java
Labels: enhancement

#63 Update fungsi ubah status employee
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Employee.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestServiceImpl.java
Labels: enhancement

#65 Greta/uc7 menyetujui bukti
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/BuktiPelaksanaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/PersetujuanBuktiPelaksanaanDTO.java
Labels: enhancement

#67 Frontend: Login and Logout Design
  FrontEnd/src/App.css
  FrontEnd/src/App.js
  FrontEnd/src/Components/Form/LoginForm.jsx
  FrontEnd/src/Components/Form/LoginForm.module.css
  FrontEnd/src/Components/LogoTag/LogoTag.jsx
  FrontEnd/src/Components/LogoTag/LogoTag.module.css
  FrontEnd/src/Components/SideNav/SideNav.jsx
  FrontEnd/src/Components/SideNav/SideNav.module.css
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.module.css
  FrontEnd/src/pages/index.jsx
  FrontEnd/src/pages/login.jsx
Labels: enhancement

#69 Frontend : Button Component Update
  FrontEnd/src/App.css
  FrontEnd/src/Components/Button/SirioButton.jsx
  FrontEnd/src/Components/Button/SirioButton.module.css
  FrontEnd/src/Components/Button/SirioDatePickerButton.jsx
  FrontEnd/src/Components/Button/TableButton.jsx
  FrontEnd/src/Components/Button/TableButton.module.css
  FrontEnd/src/Components/Form/LoginForm.jsx
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
  FrontEnd/src/pages/login.jsx
Labels: enhancement

#70 Backend and Frontend: Login Logout
  BackEnd/pom.xml
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Employee.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/EmployeeDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/DatabaseLoader.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/security/UserDetailsServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/security/WebSecurityConfig.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestServiceImpl.java
  FrontEnd/src/App.css
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.module.css
  FrontEnd/src/Components/Tables/SirioTable.jsx
  FrontEnd/src/Components/Tables/SirioTable.module.css
Labels: enhancement

#72 Fix some function does not work because cors and csrf
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/security/WebSecurityConfig.java
Labels: bug

#73 Complete Login Logout Mechanism
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/EmployeeRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/EmployeeDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/security/WebSecurityConfig.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestServiceImpl.java
  FrontEnd/package-lock.json
  FrontEnd/package.json
  FrontEnd/src/App.js
  FrontEnd/src/Components/Form/LoginForm.jsx
  FrontEnd/src/Services/AuthenticationService.jsx
  FrontEnd/src/pages/index.jsx
  FrontEnd/src/pages/login.jsx
  FrontEnd/src/pages/logout.jsx
Labels: enhancement

#75 Frontend: Generalisasi SideNav
  FrontEnd/src/Components/Button/SirioButton.jsx
  FrontEnd/src/Components/Form/LoginForm.jsx
  FrontEnd/src/Components/SideNav/LoginSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/AdministratorSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/BranchManagerSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/ManagerOperationalSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/QALeadSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/QAOfficerSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/SupervisorSideNav.jsx
  FrontEnd/src/Components/SideNav/SideNav.jsx
  FrontEnd/src/Components/SideNav/SideNavFramework.jsx
  FrontEnd/src/Components/SideNav/SideNavFramework.module.css
  FrontEnd/src/Components/SideNav/SirioSideNav.jsx
  FrontEnd/src/Layout/SirioMainLayout.jsx
  FrontEnd/src/Layout/SirioMainLayout.module.css
  FrontEnd/src/Services/AuthenticationService.jsx
  FrontEnd/src/pages/DaftarRekomendasi.jsx
  FrontEnd/src/pages/login.jsx
Labels: enhancement

#83 Frontend: Komponen Popup General
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/DatabaseLoader.java
  FrontEnd/public/favicon.ico
  FrontEnd/public/logo192.png
  FrontEnd/public/logo512.png
  FrontEnd/public/modal-checklist.png
  FrontEnd/public/trashbin.svg
  FrontEnd/src/Components/Button/ActionButton/ActionButton.module.css
  FrontEnd/src/Components/Button/ActionButton/SirioConfirmButton.jsx
  FrontEnd/src/Components/Button/ActionButton/SirioMessageButton.jsx
  FrontEnd/src/Components/Button/ActionButton/SirioWarningButton.jsx
  FrontEnd/src/pages/index.jsx
Labels: enhancement

#87 Revisi Response Login Backend
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/EmployeeRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Employee.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Role.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/EmployeeDTO.java
  FrontEnd/src/Components/Form/LoginForm.jsx
Labels: enhancement

#81 Cloud/uc10 mengelola user dan profil employee
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/EmployeeRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/HasilPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Employee.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/EmployeeDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/EmployeeDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/security/UserDetailsServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestServiceImpl.java
Labels: enhancement

#80 Nabilla/uc9 mengelola kantor cabang
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/KantorCabangRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RencanaPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/TugasPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/KantorCabang.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/KantorCabangDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/RencanaPemeriksaanDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/KantorCabangDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/RencanaPemeriksaanDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/TugasPemeriksaanDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KantorCabangRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RencanaPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RencanaPemeriksaanRestServiceImpl.java
  BackEnd/src/main/resources/application.properties
Labels: enhancement

#78 Feat/mengelola rencana
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/KantorCabangRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RencanaPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/TugasPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/TugasPemeriksaanDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/EmployeeDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/KantorCabangDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/TugasPemeriksaanDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TugasPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TugasPemeriksaanRestServiceImpl.java
Labels: enhancement

#89 Resolve Bug where nama Role > 20 character
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Role.java
Labels: bug

#90 Dina/registrasi-risiko
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RisikoRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/KomponenPemeriksaanDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/RisikoDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KomponenPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KomponenPemeriksaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RisikoRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RisikoRestServiceImpl.java
  BackEnd/src/main/resources/application.properties
Labels: enhancement

#96 Frontend: Komponen Dropdown Navigasi
  FrontEnd/package.json
  FrontEnd/public/manifest.json
  FrontEnd/src/App.css
  FrontEnd/src/Components/Button/SirioDatePickerButton.jsx
  FrontEnd/src/Components/Button/SirioDatePickerCustomInput.jsx
  FrontEnd/src/Components/Dropdown/SirioDropdown.jsx
  FrontEnd/src/Components/Dropdown/SirioDropdown.module.css
  FrontEnd/src/Components/Dropdown/SirioDropdownItem.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/ManagerOperationalSideNav.jsx
  FrontEnd/src/Components/SideNav/SideNavFramework.jsx
  FrontEnd/src/Components/SideNav/SideNavFramework.module.css
  FrontEnd/src/Components/SideNav/SirioSideNav.jsx
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
Labels: enhancement

#94 Greta/uc7 menyetujui bukti
  FrontEnd/src/App.js
  FrontEnd/src/Components/Tables/BuktiPelaksanaan/TabelBuktiPelaksanaan.jsx
  FrontEnd/src/pages/DaftarBuktiPelaksanaan.jsx
  FrontEnd/src/pages/index.jsx
Labels: enhancement

#92 Feat/mengelola bukti pelaksanaan
  FrontEnd/.gitignore
  FrontEnd/src/App.js
  FrontEnd/src/Components/DetailPages/BuktiPelaksanaan/DetailBukti.jsx
  FrontEnd/src/Components/DetailPages/BuktiPelaksanaan/DetailBukti.module.css
  FrontEnd/src/Components/DetailPages/SirioDetailPage.jsx
  FrontEnd/src/Components/DetailPages/SirioDetailPage.module.css
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasiBM.jsx
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasiBM.module.css
  FrontEnd/src/pages/BranchManager/DaftarRekomendasi.jsx
  FrontEnd/src/pages/BranchManager/DetailBuktiPelaksanaan.jsx
  FrontEnd/src/pages/index.jsx
Labels: enhancement

#100 Frontend: Menambahkan komponen button di sebelah kanan table title
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
  FrontEnd/src/Components/Tables/SirioTable.jsx
  FrontEnd/src/Components/Tables/SirioTable.module.css
Labels: enhancement

#101 Frontend: General Form
  FrontEnd/src/App.css
  FrontEnd/src/App.js
  FrontEnd/src/Components/Form/SirioForm.jsx
  FrontEnd/src/Components/Form/SirioForm.module.css
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.module.css
  FrontEnd/src/Layout/SirioMainLayout.module.css
  FrontEnd/src/pages/form.jsx
  FrontEnd/src/pages/formPage.jsx
  FrontEnd/src/pages/index.jsx
Labels: enhancement

#102 Frontend: Dokumentasi
  FrontEnd/src/App.js
  FrontEnd/src/Components/Button/ActionButton/SirioConfirmButton.jsx
  FrontEnd/src/Components/Button/ActionButton/SirioMessageButton.jsx
  FrontEnd/src/Components/Button/ActionButton/SirioWarningButton.jsx
  FrontEnd/src/Components/Button/SirioButton.jsx
  FrontEnd/src/Components/Dropdown/SirioDropdown.jsx
  FrontEnd/src/Components/Dropdown/SirioDropdownItem.jsx
  FrontEnd/src/Components/Form/LoginForm.jsx
  FrontEnd/src/Components/Form/SirioForm.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.jsx
  FrontEnd/src/Components/LogoTag/LogoTag.jsx
  FrontEnd/src/Components/SideNav/LoginSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/AdministratorSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/BranchManagerSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/ManagerOperationalSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/QALeadSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/QAOfficerSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/SuperQASideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/SuperuserSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/SupervisorSideNav.jsx
  FrontEnd/src/Components/SideNav/SideNavFramework.jsx
  FrontEnd/src/Components/SideNav/SirioSideNav.jsx
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
  FrontEnd/src/Components/Tables/SirioTable.jsx
  FrontEnd/src/Layout/SirioMainLayout.jsx
  FrontEnd/src/Services/AuthenticationService.jsx
  FrontEnd/src/pages/DaftarRekomendasi.jsx
  FrontEnd/src/pages/error.jsx
  FrontEnd/src/pages/form.jsx
  FrontEnd/src/pages/formPage.jsx
  FrontEnd/src/pages/index.jsx
  FrontEnd/src/pages/login.jsx
  FrontEnd/src/pages/logout.jsx
Labels: documentation

#107 Nathanael/general frontend
  FrontEnd/src/Components/Form/DemoForm/DemoForm.jsx
  FrontEnd/src/Components/Form/LoginForm.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.module.css
  FrontEnd/src/Services/AuthenticationService.jsx
  FrontEnd/src/pages/formPage.jsx
Labels: enhancement

#108 Minor: fix warning, refactor, and improve axios
  FrontEnd/src/App.js
  FrontEnd/src/Components/DetailPages/BuktiPelaksanaan/DetailBukti.jsx
  FrontEnd/src/Components/DetailPages/SirioDetailPage.jsx
  FrontEnd/src/Components/Form/LoginForm.jsx
  FrontEnd/src/Components/Tables/BuktiPelaksanaan/TabelBuktiPelaksanaan.jsx
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
  FrontEnd/src/Services/AuthenticationService.jsx
  FrontEnd/src/Services/RekomendasiService.jsx
  FrontEnd/src/Services/SirioAxiosBase.jsx
  FrontEnd/src/pages/QAOfficer/DaftarRekomendasi.jsx
  FrontEnd/src/pages/index.jsx
Labels: bug, change of directory, documentation, enhancement

#106 feat: Front End Registrasi Risiko-Tabel
  FrontEnd/src/App.js
  FrontEnd/src/Components/DetailPages/RegistrasiRisiko/DetailRisiko.jsx
  FrontEnd/src/Components/DetailPages/RegistrasiRisiko/DetailRisiko.module.css
  FrontEnd/src/Components/DetailPages/SirioDetailPage2Buttons.jsx
  FrontEnd/src/Components/Tables/RegistrasiRisiko/TabelRisiko.jsx
  FrontEnd/src/pages/ManagerOR/DetailRisiko.jsx
  FrontEnd/src/pages/ManagerOR/RegistrasiRisiko.jsx
  FrontEnd/src/pages/index.jsx
Labels: enhancement

#109 UseCase: Tenggat Waktu 50%
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/EmployeeRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RekomendasiRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/security/WebConfig.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/security/WebSecurityConfig.java
  BackEnd/src/main/resources/application.properties
  FrontEnd/src/Components/Button/SirioDatePickerButton.jsx
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
  FrontEnd/src/Services/RekomendasiService.jsx
Labels: enhancement

#111 Frontend: Reminder
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RekomendasiRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/ReminderRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/RekomendasiDTO.java
  FrontEnd/src/App.js
  FrontEnd/src/Components/Button/SirioButton.jsx
  FrontEnd/src/Components/Button/SirioButton.module.css
  FrontEnd/src/Components/Form/LoginForm.jsx
  FrontEnd/src/Components/Route/AuthorizedRoute.jsx
  FrontEnd/src/Components/SideNav/SideNavFramework.jsx
  FrontEnd/src/Components/SideNav/SideNavFramework.module.css
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
  FrontEnd/src/Components/Tables/Reminder/TabelReminder.jsx
  FrontEnd/src/Components/Tables/SirioTable.jsx
  FrontEnd/src/Layout/SirioMainLayout.module.css
  FrontEnd/src/Services/AuthenticationService.jsx
  FrontEnd/src/Services/ReminderService.jsx
  FrontEnd/src/pages/QAOfficer/Reminder.jsx
Labels: enhancement

#115 UseCase: Tenggat Waktu dan Reminder Complete
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RekomendasiRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/ReminderRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Rekomendasi.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Reminder.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/ReminderDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/RekomendasiDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/ReminderDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/Settings.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderRestServiceImpl.java
  FrontEnd/src/Components/Button/ActionButton/SirioConfirmButton.jsx
  FrontEnd/src/Components/Button/ActionButton/SirioMessageButton.jsx
  FrontEnd/src/Components/Button/ActionButton/SirioWarningButton.jsx
  FrontEnd/src/Components/Button/SirioDatePickerButton.jsx
  FrontEnd/src/Components/Button/SirioDatePickerButton.module.css
  FrontEnd/src/Components/Button/SirioDatePickerCustomInput.jsx
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
  FrontEnd/src/Components/Tables/Reminder/TabelReminder.jsx
  FrontEnd/src/Components/Tables/SirioTable.jsx
  FrontEnd/src/Components/Tables/SirioTable.module.css
  FrontEnd/src/Services/ReminderService.jsx
  FrontEnd/src/Services/SirioAxiosBase.jsx
Labels: enhancement

#116 Cloud/uc1 hasil pemeriksaan
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/HasilPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/HasilPemeriksaanDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/DatabaseLoader.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/HasilPemeriksaanDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/KomponenPemeriksaanDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/PersetujuanHasilPemeriksaanDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/RisikoDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/TabelHasilPemeriksaanDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/TugasPemeriksaanDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/HasilPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/HasilPemeriksaanRestServiceImpl.java
  FrontEnd/src/App.js
  FrontEnd/src/Components/Tables/HasilPemeriksaan/TabelHasilPemeriksaan.jsx
  FrontEnd/src/Components/Tables/HasilPemeriksaan/TabelHasilPemeriksaan.module.css
  FrontEnd/src/pages/DaftarHasilPemeriksaan.jsx
Labels: enhancement

#117 Cloud/uc1 hasil pemeriksaan
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/HasilPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RisikoRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/TugasPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/KantorCabang.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Risiko.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/RisikoDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/RisikoDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/TugasPemeriksaanDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RisikoRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RisikoRestServiceImpl.java
  FrontEnd/src/App.js
  FrontEnd/src/Components/Tables/HasilPemeriksaan/TabelHasilPemeriksaan.jsx
  FrontEnd/src/Components/Tables/TugasPemeriksaan/TabelTugasPemeriksaan.jsx
  FrontEnd/src/Components/Tables/TugasPemeriksaan/TabelTugasPemeriksaan.module.css
  FrontEnd/src/Services/HasilPemeriksaanService.jsx
  FrontEnd/src/Services/TugasPemeriksaanService.jsx
  FrontEnd/src/pages/QAOfficer/DaftarHasilPemeriksaan.jsx
  FrontEnd/src/pages/QAOfficer/DaftarTugasPemeriksaan.jsx
Labels: enhancement

#119 Frontend: Detail Page Improvement
  FrontEnd/src/App.js
  FrontEnd/src/Components/DetailPages/BuktiPelaksanaan/DetailBukti.jsx
  FrontEnd/src/Components/DetailPages/BuktiPelaksanaan/DetailBukti.module.css
  FrontEnd/src/Components/DetailPages/BuktiPelaksanaan/DetailPersetujuanBukti.jsx
  FrontEnd/src/Components/DetailPages/SirioDetailPage.jsx
  FrontEnd/src/Components/DetailPages/SirioDetailPage.module.css
  FrontEnd/src/Components/Form/BuktiPelaksanaan/FormFeedbackBukti.jsx
  FrontEnd/src/Components/Form/SirioForm.jsx
Labels: enhancement
