Repository Argonaut-B04/SIRIO, pull requests merged in 2020-04, with the labels that each got.

#120 Frontend: SirioForm Header
  FrontEnd/src/Components/Dropdown/SirioSelect.jsx
  FrontEnd/src/Components/Form/DemoForm/DemoForm.jsx
  FrontEnd/src/Components/Form/SirioForm.jsx
  FrontEnd/src/Components/Form/SirioForm.module.css
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.jsx
Labels: enhancement

#122 Cloud/uc10 mengelola user dan profil employee
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/EmployeeRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RoleRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/BuktiPelaksanaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Employee.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/HasilPemeriksaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/KantorCabang.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Rekomendasi.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Reminder.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/RencanaPemeriksaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/RiskLevel.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/RiskRating.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/SOP.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/TemuanRisiko.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/TugasPemeriksaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/DatabaseLoader.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/EmployeeDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestServiceImpl.java
  FrontEnd/src/App.js
  FrontEnd/src/Components/Form/Employee/EmployeeFormTambah.jsx
  FrontEnd/src/Components/Tables/Employee/TabelEmployee.jsx
  FrontEnd/src/Components/Tables/Employee/TabelEmployee.module.css
  FrontEnd/src/Services/EmployeeService.jsx
  FrontEnd/src/Services/RoleService.jsx
  FrontEnd/src/pages/Administrator/DaftarEmployee.jsx
  FrontEnd/src/pages/Administrator/FormTambahEmployee.jsx
Labels: enhancement

#123 Cloud/uc10 mengelola user dan profil employee
  FrontEnd/src/App.js
  FrontEnd/src/Components/DetailPages/Employee/DetailEmployee.jsx
  FrontEnd/src/Services/EmployeeService.jsx
  FrontEnd/src/pages/Administrator/DetailEmployee.jsx
Labels: enhancement

#124 Frontend: Header Component
  FrontEnd/src/Components/Form/DemoForm/DemoForm.jsx
  FrontEnd/src/Components/Form/SirioForm.jsx
  FrontEnd/src/Components/Form/SirioForm.module.css
  FrontEnd/src/Components/Form/SirioFormWithDetail.jsx
  FrontEnd/src/Components/Form/SirioFormWithDetail.module.css
  FrontEnd/src/Components/Header/SirioComponentHeader.jsx
  FrontEnd/src/Components/Header/SirioComponentHeader.module.css
  FrontEnd/src/Components/Tables/SirioTable.jsx
  FrontEnd/src/Components/Tables/SirioTable.module.css
Labels: enhancement

#126 UseCase: Konfigurasi Risk Level
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RiskLevelRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/RiskLevel.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/RiskLevelDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RiskLevelRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RiskLevelRestServiceImpl.java
  FrontEnd/package-lock.json
  FrontEnd/package.json
  FrontEnd/src/App.js
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.jsx
  FrontEnd/src/Components/Tables/RiskLevel/TableRiskLevel.jsx
  FrontEnd/src/Components/Tables/SirioTable.jsx
  FrontEnd/src/Services/RiskLevelService.jsx
  FrontEnd/src/pages/ManagerOR/RiskLevel.jsx
  FrontEnd/src/pages/index.jsx
Labels: enhancement

#127 Greta/all bukti pelaksanaan
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/BuktiPelaksanaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RekomendasiRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/BuktiPelaksanaanDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/KantorCabangDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/BuktiPelaksanaanDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/RekomendasiDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/BuktiPelaksanaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/BuktiPelaksananRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KantorCabangRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KantorCabangRestServiceImpl.java
  FrontEnd/src/Components/DetailPages/BuktiPelaksanaan/DetailBukti.jsx
  FrontEnd/src/Components/Form/BuktiPelaksanaan/FormBukti.jsx
  FrontEnd/src/Components/Tables/BuktiPelaksanaan/TabelBuktiPelaksanaan.jsx
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasiBM.jsx
  FrontEnd/src/Services/BuktiPelaksanaanService.jsx
Labels: documentation, enhancement

#129 UseCase: Konfigurasi Risk Rating
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RiskRatingRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RiskRatingRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RiskRatingRestServiceImpl.java
  FrontEnd/src/App.js
  FrontEnd/src/Components/Tables/RiskRating/TableRiskRating.jsx
  FrontEnd/src/Services/RiskRatingService.jsx
  FrontEnd/src/pages/ManagerOR/RiskRating.jsx
  FrontEnd/src/pages/index.jsx
Labels: enhancement

#130 Cloud/uc10 mengelola user dan profil employee
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/HasilPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/KomponenPemeriksaanDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/TugasPemeriksaanDTO.java
  FrontEnd/src/App.js
  FrontEnd/src/Components/Button/SirioButton.jsx
  FrontEnd/src/Components/Button/SirioButton.module.css
  FrontEnd/src/Components/DetailPages/HasilPemeriksaan/DetailHasilPemeriksaan.jsx
  FrontEnd/src/Components/DetailPages/SirioDetailPage.jsx
  FrontEnd/src/Components/DetailPages/SirioDetailPage.module.css
  FrontEnd/src/Components/Form/Employee/EmployeeFormTambah.jsx
  FrontEnd/src/Components/Tables/HasilPemeriksaan/TabelHasilPemeriksaan.jsx
  FrontEnd/src/Services/EmployeeService.jsx
  FrontEnd/src/Services/HasilPemeriksaanService.jsx
  FrontEnd/src/pages/QAOfficer/DetailHasilPemeriksaan.jsx
Labels: enhancement

#134 Frontend: Form inside of Form
  FrontEnd/src/Components/Form/DemoForm/DemoForm.jsx
  FrontEnd/src/Components/Form/SirioForm.jsx
  FrontEnd/src/Components/Form/SirioForm.module.css
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.module.css
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasiBM.jsx
  FrontEnd/src/Components/Tables/SirioTable.jsx
  FrontEnd/src/Components/Tables/SirioTable.module.css
  FrontEnd/src/Layout/ComponentWrapper.jsx
  FrontEnd/src/Layout/ComponentWrapper.module.css
Labels: enhancement

#135 Frontend: Multiple Form
  FrontEnd/src/App.js
  FrontEnd/src/Components/Button/SirioButton.jsx
  FrontEnd/src/Components/Form/DemoForm/DemoForm.jsx
  FrontEnd/src/Components/Form/DemoForm/DemoMultiForm.jsx
  FrontEnd/src/Components/Form/SirioForm.jsx
  FrontEnd/src/pages/formMultiPage.jsx
  FrontEnd/src/pages/index.jsx
Labels: enhancement

#136 Frontend: Better Url Config and Side Nav
  FrontEnd/src/App.js
  FrontEnd/src/Components/Error/ErrorDetail.jsx
  FrontEnd/src/Components/Error/ErrorDetail.module.css
  FrontEnd/src/Components/SideNav/RoleSideNav/AdministratorSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/BranchManagerSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/GuestSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/ManagerOperationalSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/QALeadSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/QAOfficerSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/SuperQASideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/SuperuserSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/SupervisorSideNav.jsx
  FrontEnd/src/Components/SideNav/SideNavFramework.jsx
  FrontEnd/src/Components/SideNav/SideNavFramework.module.css
  FrontEnd/src/Components/SideNav/SirioSideNav.jsx
  FrontEnd/src/Configuration/UrlConfig.jsx
  FrontEnd/src/Layout/SirioMainLayout.jsx
  FrontEnd/src/Layout/SirioMainLayout.module.css
  FrontEnd/src/index.css
  FrontEnd/src/pages/Errors/Error401.jsx
  FrontEnd/src/pages/Errors/Error404.jsx
  FrontEnd/src/pages/error.jsx
  FrontEnd/src/pages/index.jsx
  FrontEnd/src/pages/login.jsx
Labels: enhancement

#137 Backend: Permission Table
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RekomendasiRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/ReminderRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RiskLevelRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RiskRatingRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/AccessPermissions.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Role.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/AccessPermissionDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/AccessPermissionRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/AccessPermissionRestServiceImpl.java
Labels: enhancement

#138 Frontend: Perbaikan Tenggat Waktu dan Reminder
  FrontEnd/src/Components/Button/SirioButton.module.css
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
  FrontEnd/src/Components/Tables/Reminder/TabelReminder.jsx
Labels: enhancement

#139 fix: bug on SirioForms after implement multiForm
  FrontEnd/src/Components/Dropdown/SirioSelect.jsx
  FrontEnd/src/Components/Form/DemoForm/DemoForm.jsx
  FrontEnd/src/Components/Form/DemoForm/DemoMultiForm.jsx
  FrontEnd/src/Components/Form/SirioForm.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.module.css
Labels: bug

#140 feat: Set Datepicker Constraint
  FrontEnd/src/Components/Button/SirioDatePickerButton.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/GuestSideNav.jsx
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
  FrontEnd/src/Components/Tables/Reminder/TabelReminder.jsx
  FrontEnd/src/Components/Tables/SirioTable.jsx
Labels: enhancement

#141 Frontend: SirioForm per field Validation
  FrontEnd/src/Components/Dropdown/SirioSelect.jsx
  FrontEnd/src/Components/Form/DemoForm/DemoForm.jsx
  FrontEnd/src/Components/Form/SirioForm.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.module.css
Labels: enhancement

#142 Feat: now back button on detail page is optional
  FrontEnd/src/Components/DetailPages/SirioDetailPage.jsx
Labels: enhancement

#143 feat: add persetujuan hasil pemeriksaan function and page in frontend…
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/HasilPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/HasilPemeriksaanDTO.java
  FrontEnd/src/App.js
  FrontEnd/src/Components/DetailPages/HasilPemeriksaan/DetailHasilPemeriksaan.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormTolak.jsx
  FrontEnd/src/Components/Tables/HasilPemeriksaan/TabelHasilPemeriksaan.jsx
  FrontEnd/src/Components/Tables/TugasPemeriksaan/TabelTugasPemeriksaan.jsx
  FrontEnd/src/Services/HasilPemeriksaanService.jsx
  FrontEnd/src/pages/QAOfficer/FormTolakHasilPemeriksaan.jsx
Labels: enhancement

#146 Frontend: Fix SirioTable and SirioField MultiField Support
  FrontEnd/src/Components/Dropdown/SirioSelect.jsx
  FrontEnd/src/Components/Form/DemoForm/DemoForm.jsx
  FrontEnd/src/Components/Form/SirioForm.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.module.css
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
  FrontEnd/src/Components/Tables/Reminder/TabelReminder.jsx
  FrontEnd/src/Components/Tables/SirioTable.jsx
Labels: bug, enhancement

#147 fix: incorrect validate trigger
  FrontEnd/src/Components/Form/DemoForm/DemoForm.jsx
Labels: bug, enhancement

#148 Frontend: Fix warnings and multifield
  FrontEnd/src/Components/Form/DemoForm/DemoForm.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.jsx
  FrontEnd/src/Components/Tables/TugasPemeriksaan/TabelTugasPemeriksaan.jsx
Labels: enhancement

#149 fix: checkbox does not checked when value is true
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.jsx
Labels: bug, enhancement

#150 Cloud/uc1 hasil pemeriksaan
  FrontEnd/src/App.js
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormTambah.jsx
  FrontEnd/src/Services/HasilPemeriksaanService.jsx
  FrontEnd/src/Services/RisikoService.jsx
  FrontEnd/src/pages/QAOfficer/FormTambahHasilPemeriksaan.jsx
Labels: enhancement

#145 Greta/all bukti pelaksanaan
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/BuktiPelaksanaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RekomendasiRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/BuktiPelaksanaanDTO.java
  FrontEnd/src/App.css
  FrontEnd/src/App.js
  FrontEnd/src/Components/DetailPages/BuktiPelaksanaan/DetailBuktiPelaksanaan.jsx
  FrontEnd/src/Components/Form/BuktiPelaksanaan/FormBukti.jsx
  FrontEnd/src/Components/Form/BuktiPelaksanaan/FormFeedbackBukti.jsx
  FrontEnd/src/Components/Form/BuktiPelaksanaan/FormTambahBukti.jsx
  FrontEnd/src/Components/Form/BuktiPelaksanaan/FormTolakBukti.jsx
  FrontEnd/src/Components/Form/BuktiPelaksanaan/FormUbahBukti.jsx
  FrontEnd/src/Components/Form/DemoForm/DemoForm.jsx
  FrontEnd/src/Components/Form/SirioForm.jsx
  FrontEnd/src/Components/Tables/BuktiPelaksanaan/TabelBuktiPelaksanaan.jsx
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasiBM.jsx
  FrontEnd/src/Services/BuktiPelaksanaanService.jsx
  FrontEnd/src/pages/BranchManager/BuktiPelaksanaanDetail.jsx
  FrontEnd/src/pages/BranchManager/TambahBuktiForm.jsx
  FrontEnd/src/pages/BranchManager/UbahBuktiForm.jsx
  FrontEnd/src/pages/QAOfficer/DetailPersetujuanBukti.jsx
  FrontEnd/src/pages/QAOfficer/TolakBuktiForm.jsx
  FrontEnd/src/pages/index.jsx
Labels: enhancement

#152 Frontend: fix merge errors and improve multiform button
  FrontEnd/.gitignore
  FrontEnd/public/add_24px.png
  FrontEnd/public/delete_outline_24px.png
  FrontEnd/src/App.js
  FrontEnd/src/Components/Button/SirioRectangularButton.jsx
  FrontEnd/src/Components/Button/SirioRectangularButton.module.css
  FrontEnd/src/Components/Form/DemoForm/DemoForm.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.module.css
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasiBM.jsx
  FrontEnd/src/logo.svg
Labels: bug, enhancement

#153 Frontend: bug fixes and minor refactor
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RekomendasiRestController.java
  FrontEnd/src/Components/Button/SirioButton.jsx
  FrontEnd/src/Components/Button/SirioButton.module.css
  FrontEnd/src/Components/Form/DemoForm/DemoForm.jsx
  FrontEnd/src/Components/Form/SirioForm.jsx
  FrontEnd/src/Components/SideNav/SideNavFramework.jsx
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
  FrontEnd/src/Components/Tables/Reminder/TabelReminder.jsx
  FrontEnd/src/Components/Tables/SirioTable.jsx
Labels: bug, enhancement

#155 Frontend: add multifield support for deleted index
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RiskLevelRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/RiskLevel.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/RiskLevelDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RiskLevelRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RiskLevelRestServiceImpl.java
  FrontEnd/src/Components/Button/SirioButton.module.css
  FrontEnd/src/Components/Form/SirioForm.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.jsx
Labels: enhancement

#157 Feat: add redirect on unauthorized
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
  FrontEnd/src/index.css
Labels: enhancement

#158 Backend: Update database loader
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/AccessPermissions.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Employee.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Role.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/DatabaseLoader.java
Labels: enhancement

#159 Database: update bukti and rekomendasi relationship
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/BuktiPelaksanaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Rekomendasi.java
Labels: enhancement

#161 fix: database loader
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/DatabaseLoader.java
Labels: bug

#162 Fix: database loader
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/DatabaseLoader.java
Labels: bug

#163 Frontend: Field Validation Alternative
  FrontEnd/src/Components/Dropdown/SirioSelect.jsx
  FrontEnd/src/Components/Form/DemoForm/DemoForm.jsx
  FrontEnd/src/Components/Form/SirioForm.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.jsx
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
Labels: enhancement

#160 Dina/registrasi risiko
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/RisikoDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RisikoRestServiceImpl.java
  FrontEnd/src/Components/Form/HierarkiRisiko/FormHierarkiRisiko.jsx
  FrontEnd/src/Components/Form/RegistrasiRisiko/FormRisiko.jsx
  FrontEnd/src/Components/Form/RegistrasiRisiko/FormRisikoUbah.jsx
  FrontEnd/src/Components/Tables/RegistrasiRisiko/TabelRisiko.jsx
Labels: bug, enhancement

#165 Frontend: new validation, refactor
  FrontEnd/src/Components/Form/DemoForm/DemoForm.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.jsx
  FrontEnd/src/Components/Form/SirioFormComponent/SirioField.module.css
Labels: enhancement

#164 Cloud/uc1 hasil pemeriksaan
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/EmployeeRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/EmployeeDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestServiceImpl.java
  FrontEnd/src/Components/Form/Employee/EmployeeFormTambah.jsx
  FrontEnd/src/Components/Form/Employee/EmployeeFormUbah.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormTambah.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormTolak.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormUbah.jsx
  FrontEnd/src/Services/EmployeeService.jsx
Labels: enhancement

#167 BackEnd: Default permissions and database loader
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/AccessPermissions.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/DatabaseLoader.java
Labels: bug, enhancement

#169 Frontend: Clean Code
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/DatabaseLoader.java
  FrontEnd/src/Components/Button/ActionButton/SirioConfirmButton.jsx
  FrontEnd/src/Components/Button/ActionButton/SirioMessageButton.jsx
  FrontEnd/src/Components/Button/ActionButton/SirioWarningButton.jsx
  FrontEnd/src/Components/Button/SirioButton.jsx
  FrontEnd/src/Components/Button/SirioButton.module.css
  FrontEnd/src/Components/Button/SirioDatePickerButton.jsx
  FrontEnd/src/Components/Button/SirioDatePickerCustomInput.jsx
  FrontEnd/src/Components/Button/SirioRectangularButton.jsx
  FrontEnd/src/Components/Button/SirioRectangularButton.module.css
  FrontEnd/src/Components/DetailPages/HasilPemeriksaan/DetailHasilPemeriksaan.jsx
  FrontEnd/src/Components/DetailPages/SirioDetailPage.jsx
  FrontEnd/src/Components/DetailPages/SirioDetailPage.module.css
  FrontEnd/src/Components/Dropdown/SirioDropdown.jsx
  FrontEnd/src/Components/Dropdown/SirioDropdown.module.css
  FrontEnd/src/Components/Dropdown/SirioDropdownItem.jsx
  FrontEnd/src/Components/Dropdown/SirioSelect.jsx
  FrontEnd/src/Components/Error/ErrorDetail.jsx
  FrontEnd/src/Components/Form/LoginForm.jsx
  FrontEnd/src/Components/Form/SirioForm.jsx
  FrontEnd/src/Components/Header/SirioComponentHeader.jsx
  FrontEnd/src/Components/LogoTag/LogoTag.jsx
  FrontEnd/src/Components/LogoTag/LogoTag.module.css
  FrontEnd/src/Components/SideNav/LoginSideNav.jsx
  FrontEnd/src/Components/SideNav/SirioSideNav.jsx
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
  FrontEnd/src/Components/Tables/Reminder/TabelReminder.jsx
  FrontEnd/src/Components/Tables/SirioTable.jsx
  FrontEnd/src/Configuration/UrlConfig.jsx
  FrontEnd/src/Services/AuthenticationService.jsx
  FrontEnd/src/pages/index.jsx
  FrontEnd/src/pages/login.jsx
  FrontEnd/src/pages/logout.jsx
Labels: Style

#170 Backend: Scheduler, Email, and Improve
  BackEnd/pom.xml
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/ReminderRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Employee.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Rekomendasi.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Reminder.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/ReminderMailFormat.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/RekomendasiDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/ReminderDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/ReminderMailFormatDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/DatabaseLoader.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/scheduled/MailScheduler.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmailRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmailRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderMailFormatRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderMailFormatRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderRestServiceImpl.java
  BackEnd/src/main/resources/application.properties
Labels: enhancement

#172 Overall Chore and Improvements
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/EmployeeRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RekomendasiRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/ReminderRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Rekomendasi.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Reminder.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/RekomendasiDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/ReminderDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/DatabaseLoader.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KantorCabangRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KantorCabangRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderRestServiceImpl.java
  FrontEnd/src/App.css
  FrontEnd/src/App.js
  FrontEnd/src/Components/Button/SirioButton.jsx
  FrontEnd/src/Components/Button/SirioButton.module.css
  FrontEnd/src/Components/Dropdown/SirioDropdownItem.jsx
  FrontEnd/src/Components/Dropdown/SirioDropdownItem.module.css
  FrontEnd/src/Components/Dropdown/SirioSelect.jsx
  FrontEnd/src/Components/Dropdown/SirioSelect.module.css
  FrontEnd/src/Components/Form/DemoForm/DemoForm.jsx
  FrontEnd/src/Components/Form/Employee/EmployeeFormTambah.jsx
  FrontEnd/src/Components/Form/Employee/EmployeeFormUbah.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormTambah.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormUbah.jsx
  FrontEnd/src/Components/Form/HierarkiRisiko/FormHierarkiRisiko.jsx
  FrontEnd/src/Components/Form/LoginForm.jsx
  FrontEnd/src/Components/Form/RegistrasiRisiko/FormRisiko.jsx
  FrontEnd/src/Components/Form/RegistrasiRisiko/FormRisikoUbah.jsx
  FrontEnd/src/Components/Form/Reminder/ReminderTemplateForm.jsx
  FrontEnd/src/Components/Header/SirioComponentHeader.jsx
  FrontEnd/src/Components/Header/SirioComponentHeader.module.css
  FrontEnd/src/Components/SideNav/SideNavFramework.module.css
  FrontEnd/src/Components/Tables/BuktiPelaksanaan/TabelBuktiPelaksanaan.jsx
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.module.css
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasiBM.jsx
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasiBM.module.css
  FrontEnd/src/Components/Tables/Reminder/TabelReminder.jsx
  FrontEnd/src/Components/Tables/SirioTable.jsx
  FrontEnd/src/Components/Tables/SirioTable.module.css
  FrontEnd/src/Configuration/UrlConfig.jsx
  FrontEnd/src/Layout/SirioMainLayout.module.css
  FrontEnd/src/pages/BranchManager/DaftarRekomendasi.jsx
Labels: enhancement

#173 Greta/all bukti pelaksanaan
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/BuktiPelaksanaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RekomendasiRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/AccessPermissions.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/BuktiPelaksanaanDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/AccessPermissionRestServiceImpl.java
  FrontEnd/src/Components/Form/BuktiPelaksanaan/FormTambahBukti.jsx
  FrontEnd/src/Components/Form/BuktiPelaksanaan/FormUbahBukti.jsx
  FrontEnd/src/Services/RekomendasiService.jsx
Labels: enhancement

#174 Cloud/uc1 hasil pemeriksaan
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/TemuanRisikoRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/HasilPemeriksaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/HasilPemeriksaanDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/KomponenPemeriksaanDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/TemuanRisikoDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/TemuanRisikoDTO.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TemuanRisikoRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TemuanRisikoRestServiceImpl.java
  FrontEnd/src/Components/Button/ActionButton/SirioConfirmButton.jsx
  FrontEnd/src/Components/DetailPages/HasilPemeriksaan/DetailHasilPemeriksaan.jsx
  FrontEnd/src/Components/Form/Employee/EmployeeFormTambah.jsx
  FrontEnd/src/Components/Form/Employee/EmployeeFormUbah.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormTambah.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormTolak.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormUbah.jsx
  FrontEnd/src/Services/TemuanRisikoService.jsx
Labels: enhancement

#175 Fix: usecase and missing imports
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RekomendasiRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderRestServiceImpl.java
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormTolak.jsx
  FrontEnd/src/Components/Tables/Reminder/TabelReminder.jsx
  FrontEnd/src/Components/Tables/SirioTable.jsx
Labels: bug, enhancement

#179 Feat: improve size per page renderer
  FrontEnd/src/Components/Button/SirioButton.module.css
  FrontEnd/src/Components/Tables/SirioTable.jsx
Labels: enhancement

#180 feat: optimizing backend
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/BuktiPelaksanaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/EmployeeRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/KantorCabangRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RekomendasiRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RencanaPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RisikoRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RiskLevelRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RiskRatingRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RoleRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/SOPRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/TemuanRisikoRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/TugasPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KantorCabangRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KantorCabangRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RencanaPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RencanaPemeriksaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RisikoRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RisikoRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RiskRatingRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RiskRatingRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TugasPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/TugasPemeriksaanRestServiceImpl.java
Labels: enhancement

#182 Fix: Merge Error and Warnings
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/KantorCabang.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/DatabaseLoader.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestServiceImpl.java
  FrontEnd/src/App.js
  FrontEnd/src/Components/DetailPages/KantorCabang/DetailKantorCabang.jsx
  FrontEnd/src/Components/DetailPages/RencanaPemeriksaan/DetailRencanaPemeriksaan.jsx
  FrontEnd/src/Components/Error/ErrorDetail.module.css
  FrontEnd/src/Components/Form/KantorCabang/FormTambahKantorCabang.jsx
  FrontEnd/src/Components/Form/KantorCabang/FormUbahKantorCabang.jsx
  FrontEnd/src/Components/Form/RencanaPemeriksaan/FormTambahRencanaPemeriksaan.jsx
  FrontEnd/src/Components/Form/RencanaPemeriksaan/FormUbahRencanaPemeriksaan.jsx
  FrontEnd/src/Components/Tables/KantorCabang/TabelKantorCabang.jsx
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
  FrontEnd/src/Components/Tables/Reminder/TabelReminder.jsx
  FrontEnd/src/pages/Errors/Error.jsx
  FrontEnd/src/pages/index.jsx
Labels: bug, enhancement

#181 Cloud/uc1 hasil pemeriksaan
  FrontEnd/src/Components/Button/ActionButton/SirioConfirmButton.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormTambah.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormTolak.jsx
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormUbah.jsx
Labels: bug

#183 Reformatting backends
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/BuktiPelaksanaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/HasilPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/KantorCabangRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RekomendasiRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/ReminderRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/StatusBuktiPelaksanaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/StatusHasilPemeriksaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/StatusRekomendasi.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/StatusRencanaPemeriksaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/DatabaseLoader.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/Settings.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/scheduled/MailScheduler.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/BuktiPelaksanaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/BuktiPelaksananRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/HasilPemeriksaanRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/HasilPemeriksaanRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/RekomendasiRestServiceImpl.java
Labels: Style, enhancement

#184 Feat: adding preloader and loader
  FrontEnd/package-lock.json
  FrontEnd/package.json
  FrontEnd/src/Components/Form/HasilPemeriksaan/HasilPemeriksaanFormTolak.jsx
  FrontEnd/src/Components/Form/LoginForm.jsx
  FrontEnd/src/Components/SideNav/SideNavFramework.jsx
  FrontEnd/src/Components/SideNav/SideNavFramework.module.css
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
  FrontEnd/src/Layout/SirioMainLayout.jsx
  FrontEnd/src/Layout/SirioMainLayout.module.css
  FrontEnd/src/pages/QAOfficer/DaftarRekomendasi.jsx
  FrontEnd/src/pages/index.jsx
  FrontEnd/src/pages/login.jsx
Labels: enhancement

#185 Frontend: Increasing UX
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/SOPRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/SirioServerRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/security/WebSecurityConfig.java
  FrontEnd/src/App.css
  FrontEnd/src/Components/Form/LoginForm.jsx
  FrontEnd/src/Components/LogoTag/LogoTag.jsx
  FrontEnd/src/Components/LogoTag/LogoTag.module.css
  FrontEnd/src/Components/SideNav/RoleSideNav/AdministratorSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/BranchManagerSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/GuestSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/ManagerOperationalSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/QALeadSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/QAOfficerSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/SuperQASideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/SuperuserSideNav.jsx
  FrontEnd/src/Components/SideNav/RoleSideNav/SupervisorSideNav.jsx
  FrontEnd/src/Components/SideNav/SideNavFramework.jsx
  FrontEnd/src/Components/SideNav/SideNavFramework.module.css
  FrontEnd/src/Layout/SirioMainLayout.jsx
  FrontEnd/src/Layout/SirioMainLayout.module.css
  FrontEnd/src/Services/PollingService.jsx
  FrontEnd/src/pages/index.jsx
  FrontEnd/src/pages/login.jsx
Labels: enhancement

#186 Feat: now sidenav is compatible with mobile device
  FrontEnd/public/fullLogoLight.png
  FrontEnd/src/App.css
  FrontEnd/src/Components/Button/SirioButton.jsx
  FrontEnd/src/Components/LogoTag/LogoTag.jsx
  FrontEnd/src/Components/SideNav/SideNavFramework.jsx
  FrontEnd/src/Components/SideNav/SideNavFramework.module.css
  FrontEnd/src/Layout/SirioMainLayout.jsx
  FrontEnd/src/Layout/SirioMainLayout.module.css
  FrontEnd/src/pages/index.jsx
Labels: enhancement

#187 Frontend: Datepicker
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/DatabaseLoader.java
  FrontEnd/package-lock.json
  FrontEnd/package.json
  FrontEnd/public/angle_left.png
  FrontEnd/public/angle_right.png
  FrontEnd/src/App.css
  FrontEnd/src/Components/Button/SirioButton.module.css
  FrontEnd/src/Components/Button/SirioDatePickerButton.jsx
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
  FrontEnd/src/Components/Tables/SirioTable.module.css
  FrontEnd/src/Layout/SirioMainLayout.jsx
Labels: enhancement

#188 Feat: menyelaraskan reminder template dan pemerbaikan reminder
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/ReminderRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Employee.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/HasilPemeriksaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Rekomendasi.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Reminder.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/ReminderTemplate.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/ReminderDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/ReminderMailFormatDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/ReminderTemplateDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/DatabaseLoader.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/scheduled/MailScheduler.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/EmployeeRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderMailFormatRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderMailFormatRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderTemplateRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/ReminderTemplateRestServiceImpl.java
  FrontEnd/src/Components/Button/SirioDatePickerButton.jsx
  FrontEnd/src/Components/Form/Reminder/ReminderTemplateForm.jsx
  FrontEnd/src/Components/Tables/Reminder/TabelReminder.jsx
  FrontEnd/src/Services/ReminderService.jsx
Labels: bug, enhancement

#189 Backend: LocalDate; Frontend: tooltip
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RencanaPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/TugasPemeriksaanRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Rekomendasi.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/TugasPemeriksaan.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/Settings.java
  FrontEnd/package-lock.json
  FrontEnd/package.json
  FrontEnd/src/App.css
  FrontEnd/src/App.js
  FrontEnd/src/Components/Button/SirioButton.jsx
  FrontEnd/src/Components/Button/SirioButton.module.css
  FrontEnd/src/Components/DetailPages/SirioDetailPage.jsx
  FrontEnd/src/Components/Dropdown/SirioDropdown.jsx
  FrontEnd/src/Components/Error/ErrorDetail.jsx
  FrontEnd/src/Components/Form/LoginForm.jsx
  FrontEnd/src/Components/Form/SirioForm.jsx
  FrontEnd/src/Components/SideNav/SideNavFramework.jsx
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
  FrontEnd/src/Components/Tables/SirioTable.jsx
  FrontEnd/src/Components/Tables/TugasPemeriksaan/TabelTugasPemeriksaan.jsx
  FrontEnd/src/Layout/SirioMainLayout.jsx
  FrontEnd/src/Services/SirioAxiosBase.jsx
  FrontEnd/src/pages/DaftarTugasPemeriksaan.jsx
  FrontEnd/src/pages/index.jsx
Labels: enhancement

#190 Feat: mobile UX and link rekomendasi to hasil
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RekomendasiRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/RekomendasiDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/ReminderDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/RekomendasiDTO.java
  FrontEnd/src/Components/DetailPages/HasilPemeriksaan/DetailHasilPemeriksaan.jsx
  FrontEnd/src/Components/DetailPages/SirioDetailPage.jsx
  FrontEnd/src/Components/Tables/BuktiPelaksanaan/TabelBuktiPelaksanaan.jsx
  FrontEnd/src/Components/Tables/Rekomendasi/TabelRekomendasi.jsx
  FrontEnd/src/Layout/SirioMainLayout.jsx
Labels: enhancement

#191 Nathanael/refactor
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/RiskRatingRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/controller/StatusRisikoRestController.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Rekomendasi.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/Risiko.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/model/StatusRisiko.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/repository/StatusRisikoDB.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/rest/DatabaseLoader.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KantorCabangRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/KantorCabangRestServiceImpl.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusRisikoRestService.java
  BackEnd/src/main/java/com/ArgonautB04/SIRIO/services/StatusRisikoRestServiceImpl.java
  FrontEnd/src/Components/Tables/RiskLevel/TableRiskLevel.jsx
  FrontEnd/src/Components/Tables/RiskRating/TableRiskRating.jsx
Labels: enhancement

#192 Feat: fix Strings
  FrontEnd/src/Components/Form/Reminder/ReminderTemplateForm.jsx
  FrontEnd/src/Components/Tables/Reminder/TabelReminder.jsx
Labels: enhancement
